-- Zanskar schema, migration 0001.
-- Conventions (see ADR 0003): TEXT UUIDs generated by the application,
-- timestamps written by the application as RFC 3339 UTC TEXT, JSON documents in TEXT (SQLite json1),
-- secrets stored only as envelope-encrypted BLOB (see ADR 0007). Partial indexes require SQLite >= 3.8..

-- ---------------------------------------------------------------- key management
CREATE TABLE key_versions (
    id          INTEGER PRIMARY KEY,
    algorithm   TEXT NOT NULL,                 -- e.g. aes-256-gcm
    kek_source  TEXT NOT NULL,                 -- local | aws-kms | vault-transit
    kek_ref     TEXT,                          -- KMS key ARN / Vault key name
    wrapped_dek BLOB NOT NULL,
    created_at  TEXT NOT NULL,
    retired_at  TEXT
);

-- ---------------------------------------------------------------- identity
CREATE TABLE identity_providers (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    type        TEXT NOT NULL CHECK (type IN ('oidc', 'ldap', 'saml')),
    config_enc  BLOB NOT NULL,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

CREATE TABLE users (
    id             TEXT PRIMARY KEY,
    username       TEXT NOT NULL UNIQUE,
    email          TEXT UNIQUE,
    display_name   TEXT NOT NULL,
    password_hash  TEXT,                       -- argon2id PHC string; NULL for external identities
    status         TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled', 'locked')),
    idp_id         TEXT REFERENCES identity_providers(id) ON DELETE SET NULL,
    external_id    TEXT,
    failed_logins  INTEGER NOT NULL DEFAULT 0,
    locked_until   TEXT,
    created_at     TEXT NOT NULL,
    updated_at     TEXT NOT NULL,
    last_login_at  TEXT,
    UNIQUE (idp_id, external_id)
);

CREATE TABLE user_roles (
    user_id  TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role     TEXT NOT NULL CHECK (role IN ('admin', 'auditor', 'user')),
    PRIMARY KEY (user_id, role)
);

CREATE TABLE groups (
    id           TEXT PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    description  TEXT NOT NULL DEFAULT '',
    idp_id       TEXT REFERENCES identity_providers(id) ON DELETE SET NULL,
    external_id  TEXT,
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL,
    UNIQUE (idp_id, external_id)
);

CREATE TABLE group_members (
    group_id  TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    user_id   TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    added_at  TEXT NOT NULL,
    PRIMARY KEY (group_id, user_id)
);
CREATE INDEX group_members_user_idx ON group_members(user_id);

CREATE TABLE mfa_totp (
    user_id       TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    secret_enc    BLOB NOT NULL,
    confirmed_at  TEXT,
    created_at    TEXT NOT NULL
);

CREATE TABLE mfa_recovery_codes (
    id         TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code_hash  TEXT NOT NULL,
    used_at    TEXT,
    created_at TEXT NOT NULL
);
CREATE INDEX mfa_recovery_codes_user_idx ON mfa_recovery_codes(user_id);

CREATE TABLE auth_sessions (
    id            TEXT PRIMARY KEY,
    user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash    TEXT NOT NULL UNIQUE,        -- SHA-256 of the opaque cookie value
    ip            TEXT NOT NULL,
    user_agent    TEXT NOT NULL DEFAULT '',
    mfa_verified  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TEXT NOT NULL,
    expires_at    TEXT NOT NULL,
    last_seen_at  TEXT NOT NULL,
    revoked_at    TEXT
);
CREATE INDEX auth_sessions_user_idx ON auth_sessions(user_id);
CREATE INDEX auth_sessions_expires_idx ON auth_sessions(expires_at);

-- ---------------------------------------------------------------- target credentials
CREATE TABLE credentials (
    id           TEXT PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    type         TEXT NOT NULL CHECK (type IN ('password', 'ssh_key', 'ssh_ca', 'domain', 'ec2_instance_connect')),
    mode         TEXT NOT NULL CHECK (mode IN ('vaulted', 'user_supplied', 'passthrough')),
    username     TEXT,                         -- NULL when user_supplied / passthrough
    domain       TEXT,                         -- Windows domain for type = domain
    secret_enc   BLOB,                        -- envelope-encrypted password / private key / CA key
    public_key   TEXT,                         -- SSH public key or CA public key, safe to display
    key_version  INTEGER REFERENCES key_versions(id),
    created_by   TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL,
    rotated_at   TEXT
);

-- ---------------------------------------------------------------- static targets
CREATE TABLE targets (
    id                    TEXT PRIMARY KEY,
    name                  TEXT NOT NULL UNIQUE,
    address               TEXT NOT NULL,       -- hostname or IP reachable from the gateway
    os_family             TEXT NOT NULL CHECK (os_family IN ('linux', 'windows', 'other')),
    ports                 TEXT NOT NULL DEFAULT '{}',  -- {"ssh":22,"rdp":3389,"vnc":5900,"winrm":5986}
    capabilities          TEXT NOT NULL DEFAULT '[]',  -- ["ssh","rdp"] as probed or declared
    host_key_fingerprint  TEXT,                -- SHA256:... of the SSH host key
    host_key_status       TEXT NOT NULL DEFAULT 'unknown' CHECK (host_key_status IN ('unknown', 'pending', 'trusted', 'changed')),
    tls_fingerprint       TEXT,                -- RDP / WinRM server certificate SHA-256
    tags                  TEXT NOT NULL DEFAULT '{}',
    status                TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    notes                 TEXT NOT NULL DEFAULT '',
    created_by            TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at            TEXT NOT NULL,
    updated_at            TEXT NOT NULL,
    last_probed_at        TEXT
);

CREATE TABLE target_credentials (
    target_id      TEXT NOT NULL REFERENCES targets(id) ON DELETE CASCADE,
    protocol       TEXT NOT NULL CHECK (protocol IN ('ssh', 'rdp', 'vnc', 'winrm')),
    credential_id  TEXT NOT NULL REFERENCES credentials(id) ON DELETE RESTRICT,
    PRIMARY KEY (target_id, protocol)
);

-- ---------------------------------------------------------------- autoscaling targets
CREATE TABLE autoscaling_groups (
    id                     TEXT PRIMARY KEY,
    name                   TEXT NOT NULL UNIQUE,
    provider               TEXT NOT NULL CHECK (provider IN ('aws')),
    region                 TEXT NOT NULL,
    external_name          TEXT NOT NULL,      -- the cloud-side ASG name
    role_arn               TEXT NOT NULL,
    external_id            TEXT NOT NULL,      -- STS ExternalId for the cross-account role
    os_family              TEXT NOT NULL CHECK (os_family IN ('linux', 'windows', 'other')),
    ports                  TEXT NOT NULL DEFAULT '{}',
    capabilities           TEXT NOT NULL DEFAULT '[]',
    address_preference     TEXT NOT NULL DEFAULT 'private' CHECK (address_preference IN ('private', 'public')),
    poll_interval_seconds  INTEGER NOT NULL DEFAULT 30,
    tags                   TEXT NOT NULL DEFAULT '{}',
    status                 TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    last_synced_at         TEXT,
    last_error             TEXT,
    created_by             TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at             TEXT NOT NULL,
    updated_at             TEXT NOT NULL
);

CREATE TABLE asg_credentials (
    asg_id         TEXT NOT NULL REFERENCES autoscaling_groups(id) ON DELETE CASCADE,
    protocol       TEXT NOT NULL CHECK (protocol IN ('ssh', 'rdp', 'vnc', 'winrm')),
    credential_id  TEXT NOT NULL REFERENCES credentials(id) ON DELETE RESTRICT,
    PRIMARY KEY (asg_id, protocol)
);

CREATE TABLE asg_instances (
    id               TEXT PRIMARY KEY,
    asg_id           TEXT NOT NULL REFERENCES autoscaling_groups(id) ON DELETE CASCADE,
    instance_id      TEXT NOT NULL,
    private_ip       TEXT,
    public_ip        TEXT,
    availability_zone TEXT,
    lifecycle_state  TEXT NOT NULL,            -- InService, Terminating, ...
    lb_health        TEXT,                     -- healthy, unhealthy, draining, NULL when no LB
    probe_health     TEXT NOT NULL DEFAULT 'unknown' CHECK (probe_health IN ('unknown', 'healthy', 'unhealthy')),
    host_key_fingerprint TEXT,
    launched_at      TEXT,
    first_seen_at    TEXT NOT NULL,
    last_seen_at     TEXT NOT NULL,
    terminated_at    TEXT,
    UNIQUE (asg_id, instance_id)
);

-- ---------------------------------------------------------------- policy
CREATE TABLE access_policies (
    id                    TEXT PRIMARY KEY,
    name                  TEXT NOT NULL UNIQUE,
    description           TEXT NOT NULL DEFAULT '',
    enabled               BOOLEAN NOT NULL DEFAULT TRUE,
    group_id              TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    target_selector       TEXT NOT NULL,      -- {"targets":[ids],"asgs":[ids],"tags":{"env":"prod"}}
    protocols             TEXT NOT NULL,      -- ["ssh","rdp"]
    time_windows          TEXT NOT NULL DEFAULT '[]',  -- [{"days":["mon"],"from":"09:00","to":"18:00","tz":"UTC"}]
    max_session_minutes   INTEGER,
    idle_timeout_minutes  INTEGER NOT NULL DEFAULT 15,
    allow_clipboard       BOOLEAN NOT NULL DEFAULT FALSE,
    allow_file_transfer   BOOLEAN NOT NULL DEFAULT FALSE,
    require_mfa           BOOLEAN NOT NULL DEFAULT TRUE,
    created_by            TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at            TEXT NOT NULL,
    updated_at            TEXT NOT NULL
);
CREATE INDEX access_policies_group_idx ON access_policies(group_id);

-- ---------------------------------------------------------------- sessions and recordings
CREATE TABLE access_sessions (
    id                        TEXT PRIMARY KEY,
    user_id                   TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    policy_id                 TEXT REFERENCES access_policies(id) ON DELETE SET NULL,
    target_id                 TEXT REFERENCES targets(id) ON DELETE SET NULL,
    asg_id                    TEXT REFERENCES autoscaling_groups(id) ON DELETE SET NULL,
    asg_instance_id           TEXT REFERENCES asg_instances(id) ON DELETE SET NULL,
    protocol                  TEXT NOT NULL CHECK (protocol IN ('ssh', 'rdp', 'vnc', 'winrm')),
    credential_id             TEXT REFERENCES credentials(id) ON DELETE SET NULL,
    client_ip                 TEXT NOT NULL,
    user_agent                TEXT NOT NULL DEFAULT '',
    started_at                TEXT NOT NULL,
    ended_at                  TEXT,
    end_reason                TEXT,            -- user_exit | idle_timeout | max_duration | admin_terminated | target_lost | failover | error
    failover_from_session_id  TEXT REFERENCES access_sessions(id) ON DELETE SET NULL,
    CHECK (target_id IS NOT NULL OR asg_instance_id IS NOT NULL)
);
CREATE INDEX access_sessions_user_idx ON access_sessions(user_id, started_at);
CREATE INDEX access_sessions_open_idx ON access_sessions(ended_at) WHERE ended_at IS NULL;

CREATE TABLE recordings (
    id               TEXT PRIMARY KEY,
    session_id       TEXT NOT NULL UNIQUE REFERENCES access_sessions(id) ON DELETE RESTRICT,
    format           TEXT NOT NULL CHECK (format IN ('asciicast', 'guac')),
    storage_uri      TEXT NOT NULL,            -- file:///... or s3://bucket/key
    size_bytes       INTEGER NOT NULL DEFAULT 0,
    sha256           TEXT,
    started_at       TEXT NOT NULL,
    finished_at      TEXT,
    retention_until  TEXT,
    created_at       TEXT NOT NULL
);

CREATE TABLE recording_views (
    id            TEXT PRIMARY KEY,
    recording_id  TEXT NOT NULL REFERENCES recordings(id) ON DELETE CASCADE,
    user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    ip            TEXT NOT NULL,
    viewed_at     TEXT NOT NULL
);
CREATE INDEX recording_views_recording_idx ON recording_views(recording_id);

-- ---------------------------------------------------------------- audit (ADR 0008)
CREATE TABLE audit_events (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    ts             TEXT NOT NULL,
    actor_user_id  TEXT,                       -- no FK: audit rows must outlive users
    actor_ip       TEXT NOT NULL DEFAULT '',
    action         TEXT NOT NULL,              -- e.g. user.login, target.create, session.start
    object_type    TEXT NOT NULL DEFAULT '',
    object_id      TEXT NOT NULL DEFAULT '',
    outcome        TEXT NOT NULL CHECK (outcome IN ('success', 'failure')),
    details        TEXT NOT NULL DEFAULT '{}',
    prev_hash      TEXT NOT NULL,
    hash           TEXT NOT NULL UNIQUE
);
CREATE INDEX audit_events_ts_idx ON audit_events(ts);
CREATE INDEX audit_events_actor_idx ON audit_events(actor_user_id, ts);
CREATE INDEX audit_events_object_idx ON audit_events(object_type, object_id);
