#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Generates THIRD_PARTY_NOTICES.md: the attribution and license text for every
# third-party component distributed inside the Zanskar binary. Two sets ship in
# the artifact: Go modules compiled into the binary, and the npm runtime
# packages bundled into the embedded web UI. Bundled assets (fonts) are listed
# in THIRD_PARTY_LICENSES.md and referenced here.
#
# The file is generated, never hand-edited: rerun this after changing
# dependencies. Copyright lines and license bodies are copied verbatim from each
# dependency's own LICENSE/NOTICE files, so the output reflects what is actually
# shipped rather than a summary.
#
# Usage: hack/gen-notices.sh > THIRD_PARTY_NOTICES.md
set -euo pipefail
cd "$(dirname "$0")/.."

# find_file <dir> <name1> <name2> ... -> prints first existing path, or nothing
find_file() {
  local dir="$1"; shift
  local n
  for n in "$@"; do
    if [ -f "$dir/$n" ]; then echo "$dir/$n"; return 0; fi
  done
  return 0
}

emit_license() {
  # emit_license <path>  -> fenced verbatim block, or a placeholder
  local f="$1"
  if [ -n "$f" ] && [ -f "$f" ]; then
    echo '```'
    cat "$f"
    echo '```'
  else
    echo '_No license file is distributed with this package; its declared license is stated above._'
  fi
}

printf '# Third-party notices\n\n'
printf 'Zanskar is distributed under the Apache License 2.0 (see `LICENSE`). The\n'
printf 'distributed binary additionally contains the third-party components below, each\n'
printf 'under its own license. This file is generated by `hack/gen-notices.sh`; do not\n'
printf 'edit it by hand.\n\n'
printf 'Bundled non-code assets (fonts) are listed in `THIRD_PARTY_LICENSES.md`.\n\n'
printf 'This file is deterministic: it changes only when dependencies change, so CI\n'
printf 'can verify it is current by regenerating and diffing.\n\n'
printf -- '---\n\n'

# ---- Go modules compiled into the binary --------------------------------------
printf '## Go modules\n\n'
printf 'The following Go modules are compiled into the `zanskar` binary. The set is\n'
printf 'the non-test dependency closure of `./cmd/zanskar`.\n\n'

# module path | version | on-disk dir (real casing, from the build cache).
# Pin the platform to the distributed artifact (linux/amd64) so the dependency
# closure — and therefore this file — is identical wherever it is generated,
# rather than reflecting the host's GOOS/GOARCH.
GOOS=linux GOARCH=amd64 go list -deps -f '{{with .Module}}{{.Path}}|{{.Version}}|{{.Dir}}{{end}}' ./cmd/zanskar \
  | sort -u | while IFS='|' read -r path ver dir; do
  [ -z "$path" ] && continue
  case "$path" in github.com/albatroxxx/zanskar*) continue;; esac
  [ -z "$dir" ] && continue
  lic="$(find_file "$dir" LICENSE LICENSE.txt LICENSE.md LICENCE License COPYING COPYING.txt)"
  notice="$(find_file "$dir" NOTICE NOTICE.txt NOTICE.md)"
  printf '### %s\n\n' "$path"
  printf '* Version: `%s`\n\n' "${ver:-(unknown)}"
  emit_license "$lic"
  printf '\n'
  if [ -n "$notice" ]; then
    printf '**NOTICE** (required by Apache-2.0 §4(d)):\n\n'
    echo '```'; cat "$notice"; echo '```'; printf '\n'
  fi
  printf -- '---\n\n'
done

# ---- npm runtime packages bundled into the web UI -----------------------------
printf '## Web (npm) packages\n\n'
printf 'The following npm packages are bundled into the embedded single-page app\n'
printf '(`web/dist`, compiled into the binary). The set is the production dependency\n'
printf 'closure; build-time-only (devDependencies) packages are not distributed.\n\n'

if [ -d web/node_modules ]; then
  ( cd web && npm ls --omit=dev --all --parseable 2>/dev/null ) | sort -u | while read -r pdir; do
    [ -z "$pdir" ] && continue
    # Only real dependencies live under a node_modules directory; this skips the
    # SPA's own root package, which npm lists first.
    case "$pdir" in *"/node_modules/"*) ;; *) continue;; esac
    [ -f "$pdir/package.json" ] || continue
    name="$(node -e "process.stdout.write(require('$pdir/package.json').name||'')" 2>/dev/null || true)"
    ver="$(node -e "process.stdout.write(require('$pdir/package.json').version||'')" 2>/dev/null || true)"
    decl="$(node -e "const p=require('$pdir/package.json');const l=p.license||p.licenses;process.stdout.write(typeof l==='string'?l:JSON.stringify(l||''))" 2>/dev/null || true)"
    [ -z "$name" ] && continue
    lic="$(find_file "$pdir" LICENSE LICENSE.txt LICENSE.md LICENCE License license LICENSE-MIT LICENSE-MIT.txt COPYING)"
    printf '### %s\n\n' "$name"
    printf '* Version: `%s`\n' "${ver:-(unknown)}"
    printf '* Declared license: `%s`\n\n' "${decl:-(unknown)}"
    emit_license "$lic"
    printf '\n---\n\n'
  done
else
  printf '_web/node_modules not present; run `npm ci` in `web/` before generating._\n\n'
fi
