// SPDX-License-Identifier: Apache-2.0

package store

import (
	"crypto/rand"
	"encoding/hex"
)

// NewID returns a random 128-bit identifier as 32 hex characters. IDs are
// generated by the application so the same code path works on both drivers
// and so an ID never leaks insertion order.
func NewID() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic("store: crypto/rand unavailable: " + err.Error())
	}
	return hex.EncodeToString(b[:])
}
