apiVersion: v1
kind: Service
metadata:
  name: {{ include "zanskar.fullname" . }}
  labels:
    {{- include "zanskar.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "zanskar.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if eq .Values.service.sessionAffinity "ClientIP" }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityTimeoutSeconds }}
  {{- end }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
